---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pack-build-builder-push-run
spec:
  #serviceAccountName: buildpacks
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git
    - name: revision
      value: main
    - name: pathInRepo
      value: /tekton/pipeline/pack-builder-image/0.1/pack-builder-image.yml

  params:
    - name: debug
      value: "true"
    - name: git-url
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git
    - name: packCmdBuilderFlags
      value:
      - "builder"
      - "create"
      - "-v"
      - "quay.io/snowdrop/ubi-builder"
      - "--config"
      - "ubi-builder.toml"
      - "--publish"

  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ubi-builder-vol
    - name: pack-workspace
      persistentVolumeClaim:
        claimName: pack-workspace-vol
    - name: data-store
      projected:
        sources:
          - secret:
              name: pack-config-toml
          - secret:
              name: quay-creds
